#!/bin/bash

cd src
dtasm --binary -o ../dist/admiral.bin admiral.dasm16

cd ../dist

xxd -ps -c 16 admiral.bin | sed -r 's/(....)/\1 /g' | sed -r 's/^([0-9a-f])(.*)/DAT \1\2/g' | sed -r 's/([0-9a-f]{4})/0x\1,/g' | sed -r 's/(.*), $/\1/g' >admiral_dat.dasm16

dtdb -c "disasm 0" admiral.bin 2> disasm.dasm16

